### ISSUE TITLE
Slow cor function

### ISSUE THREAD

**Issue by zx8754** [USCbiostats/hJAM#3]
`stats::cor()` function could be replaced by `WGCNA::cor()` function for speed up.

Related StackOverflow post that shows 20x improvement:

- https://stackoverflow.com/q/36136071/680068

To remove dependency maybe just copy/re-write the function:

- https://github.com/cran/WGCNA/blob/678c9da2b71c5b4a43cb55005224c243f411abc8/R/corFunctions.R#L114

**Comment by lailylajiang** [comment]
Changed. Thanks Tokhir!
