### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by gvegayon** [USCbiostats/hJAM#6]
(This is a follow-up of https://github.com/USCbiostats/hJAM/pull/5#issuecomment-756437335.) 
While the package only has 4 direct dependencies, indirectly it depends on about 100 other packages:

[![status](https://tinyverse.netlify.com/badge/hJAM)](https://CRAN.R-project.org/package=hJAM)

The dependencies depend on:

- ggplot2: [![status](https://tinyverse.netlify.com/badge/ggplot2)](https://CRAN.R-project.org/package=ggplot2)
- ggpubr: [![status](https://tinyverse.netlify.com/badge/ggpubr)](https://CRAN.R-project.org/package=ggpubr)
- dplyr: [![status](https://tinyverse.netlify.com/badge/dplyr)](https://CRAN.R-project.org/package=dplyr)
- reshape2: [![status](https://tinyverse.netlify.com/badge/reshape2)](https://CRAN.R-project.org/package=reshape2)

It maybe a good idea to rethink some of the dependencies.

**Comment by gvegayon** [comment]
A quick hack to this would be to move some of the dependencies to suggests. That way, if the package fails, e.g. `ggpubr`, and is removed from CRAN, hJAM can still survive without CRAN removing it.

**Comment by lailylajiang** [comment]
I see. I will address this. Thanks!

**Comment by lailylajiang** [comment]
I removed the ggpubr and dplyr.

**Comment by gvegayon** [comment]
That was quick! You still need to remove ggpubr from the Imports field in the DESCRIPTION file.

**Comment by lailylajiang** [comment]
Just removed ggpubr. Thanks George!

**Comment by gvegayon** [comment]
Closed with https://github.com/USCbiostats/hJAM/commit/b803e7b173e0e69fd3a295d31a3a56fbc8cf777c
